---
- hosts: test
  become: yes
  become_method: sudo
  gather_facts: no

  vars_files:
    - ./group_vars/vars.yml
  roles:
    - php
    - nginx
    
    
    
  handlers:
    - include: handlers/main.yml

