---
- hosts: nana-test
#common options between modules
  sudo: yes
  gather_facts: no

  vars_files:
    - ./group_vars/vars.yml
  roles:
    - php
    - nginx
    
    
    
  handlers:
    - include: handlers/main.yml

